# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekty', '0002_auto_20161107_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False},
        ),
    ]
